### PR TITLE
Export Target type from ouroboros-network, to be more convenient to users

### PR DESCRIPTION
**Pull request by smelc**
# Changelog

```yaml
- description: |
    Export Target type from ouroboros-network, to be more convenient to users
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Fixes https://github.com/IntersectMBO/cardano-api/issues/447

Fixes https://github.com/IntersectMBO/cardano-api/issues/449

# How to trust this PR

User-facing API only

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- [X] Self-reviewed the diff

### CODE REVIEW

**Review by carbolymer — COMMENTED** [review]
LGTM! I think it was @Jimbo4350's idea with reexposing stuff. I'm leaving approval to him if this is the direction we want to follow.

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
We need to discuss how we want to expose things on a module basis. Can you create an issue for this? We have strayed far from what was originally envisioned with the `Cardano.Api` and `Cardano.Api.Shelley` but I am partly to blame :).

**Comment by smelc** [comment]
@Jimbo4350> issue created: https://github.com/IntersectMBO/cardano-api/issues/449

**Review by Jimbo4350 — APPROVED** [review]

**Comment by Jimbo4350** [comment]
I think this is fine. The alternative to this would be users traversing the `ouroboros-network`. Exposing this here would likely help inform how the `ouroboros-network` can be consumed.

**Pull request merged**
